# Generated by Django 4.2.23 on 2025-10-15 11:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('practice', 'Practice'), ('streak', 'Streak'), ('mastery', 'Mastery'), ('social', 'Social'), ('special', 'Special')], max_length=20)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('requirement_type', models.CharField(max_length=20)),
                ('requirement_target', models.IntegerField()),
                ('requirement_metric', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='KidsAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('progress', models.IntegerField(default=0)),
                ('unlocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KidsLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('read_aloud', 'Read Aloud'), ('vocabulary', 'Vocabulary'), ('pronunciation', 'Pronunciation')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KidsProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('lesson_type', models.CharField(choices=[('kids', 'Kids'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('ielts', 'IELTS'), ('pte', 'PTE')], max_length=20)),
                ('content_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('pronunciation', 'Pronunciation'), ('grammar', 'Grammar'), ('conversation', 'Conversation'), ('listening', 'Listening'), ('reading', 'Reading'), ('writing', 'Writing'), ('story', 'Story')], max_length=20)),
                ('difficulty_level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('duration_minutes', models.IntegerField(default=15)),
                ('payload', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['lesson_type', 'order', 'difficulty_level'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('interest', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('subscribed', models.BooleanField(default=True)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('definition', models.TextField(blank=True)),
                ('example_sentence', models.TextField(blank=True)),
                ('mastery_level', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('times_practiced', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('first_learned', models.DateTimeField(auto_now_add=True)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('difficulty', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('category', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
                ('age_range', models.CharField(blank=True, max_length=50, null=True)),
                ('native_language', models.CharField(blank=True, max_length=100, null=True)),
                ('english_level', models.CharField(blank=True, max_length=50, null=True)),
                ('learning_purpose', models.JSONField(blank=True, default=list)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('survey_completed_at', models.DateTimeField(blank=True, null=True)),
                ('voice_speed', models.CharField(default='normal', max_length=20)),
                ('difficulty', models.CharField(default='medium', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('auto_play', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('pronunciation', 'Pronunciation'), ('conversation', 'Conversation'), ('vocabulary', 'Vocabulary'), ('grammar', 'Grammar'), ('listening', 'Listening'), ('reading', 'Reading'), ('exam_practice', 'Exam Practice')], max_length=20)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('points_earned', models.IntegerField(default=0)),
                ('words_practiced', models.IntegerField(default=0)),
                ('sentences_practiced', models.IntegerField(default=0)),
                ('mistakes_count', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(auto_now=True)),
                ('pronunciation_score', models.FloatField(blank=True, null=True)),
                ('fluency_score', models.FloatField(blank=True, null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('grammar_score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type', 'is_active'], name='api_lesson_lesson__759fe7_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['content_type'], name='api_lesson_content_22ab22_idx'),
        ),
        migrations.AddField(
            model_name='kidsprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kidsachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='vocabularyword',
            index=models.Index(fields=['user', 'mastery_level'], name='api_vocabul_user_id_a0ea5b_idx'),
        ),
        migrations.AddIndex(
            model_name='vocabularyword',
            index=models.Index(fields=['last_practiced'], name='api_vocabul_last_pr_75da8a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vocabularyword',
            unique_together={('user', 'word')},
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'unlocked'], name='api_userach_user_id_263294_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['user', 'session_date'], name='api_practic_user_id_fc5bad_idx'),
        ),
        migrations.AddIndex(
            model_name='practicesession',
            index=models.Index(fields=['session_type'], name='api_practic_session_57236e_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['user', 'completed'], name='api_lessonp_user_id_64aae3_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['last_attempt'], name='api_lessonp_last_at_82ce82_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('user', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='kidsprogress',
            unique_together={('user',)},
        ),
        migrations.AlterUniqueTogether(
            name='kidsachievement',
            unique_together={('user', 'name')},
        ),
    ]
