# Generated by Django 4.2.24 on 2025-11-03 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_emailverificationtoken'),
    ]

    operations = [
        # Create AdminNotification only (KidsCertificate already exists in DB)
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('user_registered', 'New User Registration'), ('user_activity', 'User Activity'), ('system_alert', 'System Alert'), ('maintenance', 'Maintenance'), ('security', 'Security Alert'), ('analytics', 'Analytics Update'), ('error', 'Error Report'), ('info', 'Information')], default='info', max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, help_text='Optional link to related page', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data about the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Auto-delete after this date (30 days by default)', null=True)),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Specific admin user, or null for all admins', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='api_adminno_user_id_d97447_idx'), models.Index(fields=['is_read', 'created_at'], name='api_adminno_is_read_5856b7_idx'), models.Index(fields=['expires_at'], name='api_adminno_expires_c52829_idx')],
            },
        ),
    ]
