# Generated by Django 4.2.24 on 2025-11-04 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_create_adminnotification_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('kids_4_10', 'Kids (4-10)'), ('kids_11_17', 'Kids (11-17)'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('ielts', 'IELTS'), ('pte', 'PTE')], max_length=20),
        ),
        # KidsCertificate already exists in database (created in 0003), so we don't create it again
    ]
