# Generated by Django 4.2.24 on 2025-11-04 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_lesson_lesson_type_kidscertificate'),
    ]

    operations = [
        # KidsCertificate table already exists in database (created manually or in 0003)
        # This migration is a no-op to mark the model as tracked in migrations
        migrations.RunPython(
            lambda apps, schema_editor: None,  # No-op forward function
            lambda apps, schema_editor: None,  # No-op reverse function
        ),
    ]
