# Generated by Django 4.2.24 on 2025-11-04 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_kidscertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyStepResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=50)),
                ('step_number', models.IntegerField()),
                ('response_data', models.JSONField(default=dict)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_step_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'step_number', '-completed_at'],
                'indexes': [models.Index(fields=['user', 'step_name'], name='api_surveys_user_id_117025_idx'), models.Index(fields=['user', 'step_number'], name='api_surveys_user_id_f6aa3d_idx')],
            },
        ),
    ]
