# Generated by Django 4.2.24 on 2025-11-04 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_survey_step_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='Elora', max_length=255)),
                ('support_email', models.EmailField(blank=True, default='support@elora.com', max_length=254)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('allow_registrations', models.BooleanField(default=True)),
                ('ga_id', models.CharField(blank=True, default='', max_length=32)),
                ('clarity_id', models.CharField(blank=True, default='', max_length=64)),
                ('analytics_enabled', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('two_factor_admin', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
