# Generated by Django 4.2.24 on 2025-11-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='default_theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='light', max_length=10),
        ),
    ]
