# Generated by Django 4.2.24 on 2025-11-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_platformsettings_default_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
