# Generated by Django 4.2.24 on 2025-11-06 11:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(db_index=True, max_length=100)),
                ('story_title', models.CharField(max_length=255)),
                ('word', models.CharField(max_length=100)),
                ('hint', models.TextField()),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['story_id', 'difficulty'], name='api_storywo_story_i_638b5f_idx'), models.Index(fields=['category'], name='api_storywo_categor_53acf8_idx')],
                'unique_together': {('story_id', 'word')},
            },
        ),
        migrations.CreateModel(
            name='StoryPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(db_index=True, max_length=100)),
                ('story_title', models.CharField(max_length=255)),
                ('phrase', models.CharField(max_length=500)),
                ('phonemes', models.TextField()),
                ('emoji', models.CharField(blank=True, max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['story_id', 'difficulty'], name='api_storyph_story_i_362a60_idx')],
                'unique_together': {('story_id', 'phrase')},
            },
        ),
        migrations.CreateModel(
            name='StoryEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(max_length=100)),
                ('story_title', models.CharField(max_length=255)),
                ('story_type', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('words_extracted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'completed'], name='api_storyen_user_id_7c51d4_idx'), models.Index(fields=['story_id'], name='api_storyen_story_i_e3a147_idx')],
                'unique_together': {('user', 'story_id')},
            },
        ),
        migrations.CreateModel(
            name='KidsVocabularyPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('story_id', models.CharField(blank=True, max_length=100)),
                ('best_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attempts', models.IntegerField(default=0)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_vocabulary_practice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'last_practiced'], name='api_kidsvoc_user_id_488f8e_idx'), models.Index(fields=['story_id'], name='api_kidsvoc_story_i_796d8d_idx')],
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='KidsPronunciationPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=500)),
                ('story_id', models.CharField(blank=True, max_length=100)),
                ('best_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('attempts', models.IntegerField(default=0)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_pronunciation_practice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'last_practiced'], name='api_kidspro_user_id_b87501_idx'), models.Index(fields=['story_id'], name='api_kidspro_story_i_6e383c_idx')],
                'unique_together': {('user', 'phrase')},
            },
        ),
        migrations.CreateModel(
            name='KidsGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('rhyme', 'Rhyme Game'), ('sentence', 'Sentence Builder'), ('echo', 'Echo Challenge'), ('memory', 'Memory Game'), ('word_match', 'Word Match'), ('other', 'Other')], max_length=50)),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('points_earned', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_kidsgam_user_id_dfd469_idx'), models.Index(fields=['game_type'], name='api_kidsgam_game_ty_07c044_idx')],
            },
        ),
        migrations.CreateModel(
            name='KidsFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='api_kidsfav_user_id_836025_idx')],
                'unique_together': {('user', 'story_id')},
            },
        ),
    ]
