# Generated by Django 4.2.24 on 2025-11-07 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_storyword_storyphrase_storyenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kidsgamesession',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kidsgamesession',
            name='difficulty',
            field=models.CharField(default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='kidsgamesession',
            name='game_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kidsgamesession',
            name='rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kidsgamesession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kidsgamesession',
            name='game_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='kidsgamesession',
            name='score',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
