# Generated by Django 4.2.24 on 2025-11-08 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_kidsgamesession_completed_kidsgamesession_difficulty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('system', 'System'), ('certificate', 'Certificate'), ('badge', 'Badge'), ('trophy', 'Trophy'), ('achievement', 'Achievement')], default='system', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('event_key', models.CharField(blank=True, default='', help_text='Unique key used to deduplicate notifications (e.g. certificate ID)', max_length=150)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', 'created_at'], name='api_usernot_user_id_ad0f4d_idx'), models.Index(fields=['user', 'created_at'], name='api_usernot_user_id_b5ea99_idx'), models.Index(fields=['event_key'], name='api_usernot_event_k_7c9b17_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usernotification',
            constraint=models.UniqueConstraint(condition=models.Q(('event_key__gt', '')), fields=('user', 'event_key'), name='unique_user_event_key'),
        ),
    ]
