# Generated by Django 4.2.24 on 2025-11-08 19:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0014_usernotification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentalControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(blank=True, default='', max_length=128)),
                ('daily_limit_minutes', models.IntegerField(default=30, help_text='Daily time allowance in minutes for kids mode sessions', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)])),
                ('last_pin_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parental_controls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parental Control Settings',
                'verbose_name_plural': 'Parental Control Settings',
            },
        ),
    ]
