# Generated by Django 4.2.24 on 2025-11-10 04:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_parentalcontrolsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeenProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('last_engagement', models.DateField(blank=True, null=True)),
                ('vocabulary_attempts', models.IntegerField(default=0)),
                ('pronunciation_attempts', models.IntegerField(default=0)),
                ('games_attempts', models.IntegerField(default=0)),
                ('missions_started', models.IntegerField(default=0)),
                ('missions_completed', models.IntegerField(default=0)),
                ('favorites_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teen_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teen Progress',
                'verbose_name_plural': 'Teen Progress',
            },
        ),
        migrations.CreateModel(
            name='TeenVocabularyPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('story_id', models.CharField(blank=True, max_length=100)),
                ('story_title', models.CharField(blank=True, max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('best_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teen_vocabulary_practice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'word'], name='api_teenvoc_user_id_2555de_idx'), models.Index(fields=['user', 'last_practiced'], name='api_teenvoc_user_id_36014e_idx')],
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='TeenStoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(max_length=100)),
                ('story_title', models.CharField(max_length=255)),
                ('story_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], default='started', max_length=20)),
                ('attempts', models.IntegerField(default=0)),
                ('best_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('total_points_earned', models.IntegerField(default=0)),
                ('last_started_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teen_story_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'story_id'], name='api_teensto_user_id_5a2670_idx'), models.Index(fields=['user', 'status'], name='api_teensto_user_id_8bfd0d_idx')],
                'unique_together': {('user', 'story_id')},
            },
        ),
        migrations.CreateModel(
            name='TeenPronunciationPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=500)),
                ('story_id', models.CharField(blank=True, max_length=100)),
                ('story_title', models.CharField(blank=True, max_length=255)),
                ('attempts', models.IntegerField(default=0)),
                ('best_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teen_pronunciation_practice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'phrase'], name='api_teenpro_user_id_b1c9bd_idx'), models.Index(fields=['user', 'last_practiced'], name='api_teenpro_user_id_2144f1_idx')],
                'unique_together': {('user', 'phrase')},
            },
        ),
        migrations.CreateModel(
            name='TeenFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teen_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='api_teenfav_user_id_4ce654_idx')],
                'unique_together': {('user', 'story_id')},
            },
        ),
        migrations.CreateModel(
            name='TeenAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('progress', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teen_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'key'], name='api_teenach_user_id_3ffc36_idx'), models.Index(fields=['user', 'unlocked'], name='api_teenach_user_id_b4384f_idx')],
                'unique_together': {('user', 'key')},
            },
        ),
    ]
