# Generated by Django 4.2.24 on 2025-11-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_cookieconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='practice_goal_minutes',
            field=models.IntegerField(blank=True, help_text='Daily practice goal in minutes', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='practice_start_time',
            field=models.TimeField(blank=True, help_text='Preferred daily practice start time', null=True),
        ),
    ]
