# Generated by Django 4.2.24 on 2025-11-10 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_add_practice_fields_to_userprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kidscertificate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kidscertificate',
            name='audience',
            field=models.CharField(choices=[('young', 'Young Kids (4-10)'), ('teen', 'Teen Kids (11-17)')], default='young', help_text='Target audience: young or teen', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='kidscertificate',
            unique_together={('user', 'cert_id', 'audience')},
        ),
    ]
