# Generated by Django 4.2.24 on 2025-11-10 18:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_add_audience_to_kidscertificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeenGameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(max_length=50)),
                ('game_title', models.CharField(blank=True, max_length=255)),
                ('score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('points_earned', models.IntegerField(default=0)),
                ('rounds', models.IntegerField(default=0)),
                ('difficulty', models.CharField(default='beginner', max_length=20)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teen_game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='api_teengam_user_id_ecd09a_idx'), models.Index(fields=['game_type'], name='api_teengam_game_ty_03bd74_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeenCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teen_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cert_id')},
            },
        ),
    ]
