# Generated by Django 4.2.24 on 2025-11-11 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0020_add_teen_gamesession_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(choices=[('/kids/young', 'Young Kids (4-10)'), ('/kids/teen', 'Teen Kids (11-17)'), ('/adults/beginners', 'Adults Beginners'), ('/adults/intermediates', 'Adults Intermediates'), ('/adults/advanced', 'Adults Advanced'), ('/ielts-pte', 'IELTS/PTE')], max_length=100)),
                ('required_criteria', models.JSONField(default=dict)),
                ('current_progress', models.JSONField(default=dict)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_eligibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Page Eligibility',
                'verbose_name_plural': 'Page Eligibilities',
                'indexes': [models.Index(fields=['user', 'page_path'], name='api_pageeli_user_id_accad6_idx'), models.Index(fields=['user', 'is_unlocked'], name='api_pageeli_user_id_d46b65_idx')],
                'unique_together': {('user', 'page_path')},
            },
        ),
    ]
