# Generated by Django 4.2.24 on 2025-11-11 07:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0021_add_page_eligibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('young_kids', 'Young Kids (4-10)'), ('teen_kids', 'Teen Kids (11-17)'), ('adults_beginner', 'Adults Beginner'), ('adults_intermediate', 'Adults Intermediate'), ('adults_advanced', 'Adults Advanced'), ('ielts_pte', 'IELTS/PTE')], max_length=50)),
                ('total_points', models.IntegerField(default=0)),
                ('total_streak', models.IntegerField(default=0)),
                ('lessons_completed', models.IntegerField(default=0)),
                ('practice_time_minutes', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('first_access', models.DateTimeField(auto_now_add=True)),
                ('days_active', models.IntegerField(default=0)),
                ('progress_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('level', models.IntegerField(default=1)),
                ('stories_completed', models.IntegerField(default=0)),
                ('vocabulary_words', models.IntegerField(default=0)),
                ('pronunciation_attempts', models.IntegerField(default=0)),
                ('games_completed', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category Progress',
                'verbose_name_plural': 'Category Progress',
                'ordering': ['-last_activity', '-total_points'],
                'indexes': [models.Index(fields=['user', 'category'], name='api_categor_user_id_dcbdf2_idx'), models.Index(fields=['user', 'last_activity'], name='api_categor_user_id_c515d1_idx'), models.Index(fields=['category', 'total_points'], name='api_categor_categor_6cdbf6_idx')],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
