# Generated by Django 4.2.24 on 2025-11-11 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_categoryprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='KidsTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trophy_id', models.CharField(max_length=128)),
                ('audience', models.CharField(choices=[('young', 'Young Kids (4-10)'), ('teen', 'Teen Kids (11-17)')], default='young', help_text='Target audience: young or teen', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kids_trophies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'trophy_id'], name='api_kidstro_user_id_e05e6c_idx')],
                'unique_together': {('user', 'trophy_id', 'audience')},
            },
        ),
    ]
