# Generated by Django 4.2.24 on 2025-11-17 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_kids_trophy'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='video_thumbnails/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('video_url', models.URLField(blank=True, help_text='External video URL (YouTube, Vimeo, etc.)', null=True)),
                ('duration', models.IntegerField(default=0, help_text='Duration in seconds')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('category', models.CharField(choices=[('pronunciation', 'Pronunciation'), ('conversation', 'Conversation'), ('grammar', 'Grammar'), ('business', 'Business'), ('daily', 'Daily Life')], default='conversation', max_length=20)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('views', models.IntegerField(default=0)),
                ('speaking_exercises', models.IntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Lesson',
                'verbose_name_plural': 'Video Lessons',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['slug', 'is_active'], name='api_videole_slug_54eb32_idx'), models.Index(fields=['difficulty', 'category'], name='api_videole_difficu_449c77_idx'), models.Index(fields=['is_active', 'order'], name='api_videole_is_acti_e08e7b_idx')],
            },
        ),
    ]
