# Generated by Django 4.2.24 on 2025-11-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_videolesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolesson',
            name='chapters',
            field=models.JSONField(blank=True, default=list, help_text='List of chapters with time, label, and seconds'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='full_description',
            field=models.TextField(blank=True, help_text='Full expandable description for video detail page'),
        ),
        migrations.AddField(
            model_name='videolesson',
            name='hashtags',
            field=models.JSONField(blank=True, default=list, help_text='List of hashtags for the video'),
        ),
    ]
