# Generated by Django 4.2.24 on 2025-11-17 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_add_video_detail_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoShareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(blank=True, help_text='copy_link, web_share, etc.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_share_events', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_events', to='api.videolesson')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video'], name='api_videosh_video_i_557106_idx')],
            },
        ),
        migrations.CreateModel(
            name='VideoEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('playlist_name', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_engagements', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='api.videolesson')),
            ],
            options={
                'indexes': [models.Index(fields=['video', 'liked'], name='api_videoen_video_i_10cdb9_idx'), models.Index(fields=['video', 'saved'], name='api_videoen_video_i_644107_idx')],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='PracticeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_comments', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_comments', to='api.videolesson')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video', 'is_approved'], name='api_practic_video_i_89f816_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_slug', models.SlugField(default='elora-english', max_length=120)),
                ('channel_name', models.CharField(default='Elora English', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['channel_slug', 'is_active'], name='api_channel_channel_e6f481_idx')],
                'unique_together': {('user', 'channel_slug')},
            },
        ),
    ]
